accounts/urls.py
from django import views
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    # path('profile/edit', views.profile_edit, name='profile_edit'),
    path('register', views.register_user, name='register_user'),
    # path('orders/', views.orders, name='orders'),
    # path('password/', views.change_pass, name='change_pass'),
    path('forgotPassword/', views.forgot_password, name='forgot_password'),
    path('resetpassword_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('resetPassword/', views.reset_password, name='reset_password'),
    path('companies/', include('company.urls')),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('salary.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('person/', include('person.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import (AuthenticationForm, PasswordResetForm, SetPasswordForm)

from .models import UserBase


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'نام کاربری', 'id': 'login-username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'placeholder': 'رمز عبور',
            'id': 'login-pwd',
        }
    ))


class RegistrationForm(forms.ModelForm):

    username = forms.CharField(
        label='نام کاربری', min_length=4, max_length=50, help_text='اجباری')
    email = forms.EmailField(label='ایمیل', max_length=100, help_text='اجباری', error_messages={
        'required': 'متأسفیم، وارد کردن ایمیل اجباری است!'})
    password = forms.CharField(label='رمز عبور', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='تکرار رمز عبور', widget=forms.PasswordInput)

    class Meta:
        model = UserBase
        fields = ('username', 'email',)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = UserBase.objects.filter(username=username)
        if r.count():
            raise forms.ValidationError("کاربر با این نام کاربری از قبل موجود است.")
        return username

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('رمز عبور یکسان نیست.')
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if UserBase.objects.filter(email=email).exists():
            raise forms.ValidationError(
                'لطفاً از ایمیل دیگری استفاده کنید. این ایمیل از قبل وجود دارد.')
        return email

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['username'].widget.attrs.update(
        #     {'placeholder': 'نام کاربری'})
        self.fields['email'].widget.attrs.update(
            {'name': 'email', 'id': 'id_email'})
        # self.fields['password'].widget.attrs.update(
        #     {'placeholder': 'رمز عبور'})
        # self.fields['password2'].widget.attrs.update(
        #     {'placeholder': 'تکرار رمز عبور'})

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'block w-full px-3 py-1.5 text-base font-normal text-gray-700 ' \
                                                       'bg-white bg-clip-padding border border-solid border-gray-300 ' \
                                                       'rounded transition ease-in-out mt-1 mb-4 dark:border-gray-600 ' \
                                                       'dark:bg-gray-700 focus:border-purple-400 focus:outline-none ' \
                                                       'focus:shadow-outline-purple dark:text-gray-300 ' \
                                                       'dark:focus:shadow-outline-gray form-input'


class PwdResetForm(PasswordResetForm):

    email = forms.EmailField(max_length=254, widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Email', 'id': 'form-email'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        u = UserBase.objects.filter(email=email)
        if not u:
            raise forms.ValidationError(
                'Unfortunatley we can not find that email address')
        return email


class PwdResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label='New password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-newpass'}))
    new_password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-new-pass2'}))


class UserEditForm(forms.ModelForm):

    email = forms.EmailField(
        label='Account email (can not be changed)', max_length=200, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3 text-gray-700 dark:text-gray-400', 'placeholder': 'email', 'id': 'form-email', 'readonly': 'readonly'}))

    user_name = forms.CharField(
        label='Firstname', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Username', 'id': 'form-firstname', 'readonly': 'readonly'}))

    first_name = forms.CharField(
        label='Username', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Firstname', 'id': 'form-lastname'}))

    class Meta:
        model = UserBase
        fields = ('email', 'username', 'first_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].required = True
        self.fields['email'].required = True

accounts/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.encoding import force_bytes, force_str
from django.urls import reverse
from django.contrib import messages

from person.models import Person
from .tokens import account_activation_token

from company.forms import CompanyForm
from company.models import Company
from .forms import RegistrationForm
from .models import UserBase

# from SafeBox import settings
# from accounts.forms import MyUserForm, ProfileForm, PasswordForm, RegisterForm
# from accounts.models import Profile
# from orders.models import Order

# VERIFICATION EMAIL
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage


@login_required
def dashboard(request):
    person = Person.objects.filter(company__accountant=request.user)
    company = Company.objects.filter(accountant=request.user)
    context = {
        'person': person,
        'company': company,
    }
    return render(request, 'accounts/index.html', context)


def login_view(request):
    next_url = request.GET.get('next')
    if request.method == 'POST':
        print('login for')
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=email, password=password)
        if user is not None:
            # Successful login
            login(request, user)
            redirect_url = next_url if next_url else reverse('salary:home_page')
            return HttpResponseRedirect(redirect_url)
        else:
            # undefined user or wrong password
            context = {
                'email': email,
                'error': 'کاربری با این مشخصات یافت نشد!'
            }
    else:
        context = {
        }
    return render(request, 'accounts/pages/login.html', context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('salary:home_page'))


@login_required
def profile_details(request):
    profile = request.user
    context = {
        'profile': profile
    }
    return render(request, 'accounts/profile_details.html', context)


def register_user(request):
    users = UserBase.objects.all()
    usernames = [i.username.lower() for i in users]
    emails = [i.email for i in users]
    res = None
    if request.method == 'POST':
        print('post method')
        registerForm = RegistrationForm(request.POST)
        if registerForm.is_valid():
            user = registerForm.save(commit=False)
            user.email = registerForm.cleaned_data['email']
            user.set_password(registerForm.cleaned_data['password'])
            user.is_active = False
            user.save()
            print('user saved')
            # setup email
            current_site = get_current_site(request)
            subject = 'Activate your Account'
            message = render_to_string('accounts/pages/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject=subject, message=message)
            return render(request, 'accounts/pages/create-account.html', {'res': 'ثبت نام شما با موفقیت انجام شد. '
                                                                                 'لطفاً برای تأیید حساب کاربری ایمیل '
                                                                                 'خود را چک کنید.'})
    else:
        print('get method')
        registerForm = RegistrationForm()
    return render(request, 'accounts/pages/create-account.html', {'form': registerForm})


# @login_required
# def profile_edit(request):
#     profile = request.user.profile

#     context = {
#         'profile': profile,
#     }

#     if request.method == 'POST':
#         print('in post form')
#         user_form = MyUserForm(request.POST, instance=request.user)
#         profile_form = ProfileForm(request.POST, files=request.FILES, instance=request.user.profile)
#         if user_form.is_valid() and profile_form.is_valid():
#             user_form.save()
#             profile_form.save()
#             context['message'] = 'success'
#             return JsonResponse({'data': 'اطلاعات با موفقیت ویرایش شد'}, safe=False)
#         else:
#             context['message'] = 'error'
#             return JsonResponse({'error': 'در ثبت اطلاعات خطایی رخ داده است!'}, safe=False)

#     else:
#         user_form = MyUserForm(instance=request.user)
#         profile_form = ProfileForm(instance=request.user.profile)

#     context['user_form'] = user_form
#     context['profile_form'] = profile_form

#     return render(request, 'accounts/profile_edit.html', context)


# def orders(request):
#     my_orders = Order.objects.filter(customer=request.user.profile)
#     shopping = my_orders.filter(status=1)
#     registered = my_orders.filter(status=2)

#     if request.method == 'POST':
#         order_number = request.POST.get('order_number')
#         order = Order.objects.get(order_number=order_number)
#         order.status = 3
#         order.save()

#     context = {
#         'my_orders': my_orders,
#         'shopping': shopping,
#         'registered': registered,
#     }
#     return render(request, 'accounts/my_orders.html', context)


# @login_required
# def change_pass(request):
#     profile = request.user.profile
#     message = None
#     if request.method == 'POST':
#         form = PasswordForm(request.user, request.POST)
#         if form.is_valid():
#             user = form.save()
#             update_session_auth_hash(request, user)  # Important!
#             messages.success(request, 'رمز عبور شما با موفقیت تغییر کرد!')
#             message = 'success'
#             # return redirect('accounts:change_pass')
#         else:
#             messages.error(request, 'لطفاً خطاهای زیر را تصحیح کنید.')
#             message = 'error'
#     else:
#         form = PasswordForm(request.user)

#     context = {
#         'form': form,
#         'profile': profile,
#         'message': message,
#     }
#     return render(request, 'accounts/change_pass.html', context=context)


def account_activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = UserBase.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, user.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('accounts:dashboard')
    else:
        return render(request, 'accounts/pages/activation_invalid.html')


def forgot_password(request):
    res = None
    if request.method == 'POST':
        email = request.POST['email']
        print('email: ', email)
        if UserBase.objects.filter(email=email).exists():
            user = UserBase.objects.get(email=email)

            # Reset Password
            current_site = get_current_site(request)
            mail_subject = 'بازنشانی گذرواژه'
            message = render_to_string('accounts/pages/reset_password_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            print('after message')
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            print('before send email')
            send_email.send()
            print('send email successfully')
            # END Reset Password

            # messages.success(request, 'ایمیل بازنشانی گذرواژه به آدرس ایمیل شما ارسال شد!')
            # return redirect('accounts:login')
            return render(request, 'accounts/pages/forgot-password.html', {'res': 'ایمیل بازنشانی گذرواژه به آدرس '
                                                                                  'ایمیل شما ارسال شد.'})
        else:
            # messages.error(request, 'حساب کاربری وجود ندارد!')
            return render(request, 'accounts/pages/forgot-password.html', {'error': 'حساب کاربری با ایمیل وارد شده وجود'
                                                                                  'ندارد!'})

    return render(request, 'accounts/pages/forgot-password.html')


def reset_password_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = UserBase.objects.get(pk=uid)
        print('user: ', user)
    except(TypeError, ValueError, OverflowError, user.DoesNotExist):
        user = None
        print('user empty')

    if user is not None and default_token_generator.check_token(user, token):
        print('is user')
        request.session['uid'] = uid
        messages.success(request, 'لطفاً گذرواژه خود را بازنشانی کنید!')
        return redirect('accounts:reset_password')
    else:
        print('user noting')
        messages.error(request, 'این لینک منقضی شده است!')
        return redirect('accounts:login')


def reset_password(request):
    res= None
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:

templates/accounts/pages/account_activation_email.html
{% autoescape off %}
 عزیز {{ user }} سلام

حساب کاربری شما با موفقیت ایجاد شده است. برای فعالسازی روی لینک زیر کلیک کنید.
با تشکر
    گروه نرم افزاری زیراد
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/pages/activation_invalid.html
invalid

templates/accounts/pages/login.html
{% extends 'salary/base.html' %}
{% load static %}
{% block head %}
    {% block extra_headers %}
        <head>
            <meta charset="UTF-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            <title>Login - Windmill Dashboard</title>
            <link
                    href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
                    rel="stylesheet"
            />
            <script
                    src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"
                    defer
            ></script>
            <script src="{% static 'salary/js/init-alpine.js' %}"></script>
        </head>
    {% endblock %}
{% endblock %}

{% block title %}{{ super }} حقوق و دستمزد آنلاین {% endblock %}
{% block body %}
    <html :class="{ 'theme-dark': dark }" x-data="data()" lang="en" dir="rtl">

    <div class="flex items-center min-h-screen p-6 bg-gray-50 dark:bg-gray-900">
        <div class="flex-1 h-full max-w-4xl mx-auto overflow-hidden bg-white rounded-lg shadow-xl dark:bg-gray-800">
            <div class="flex flex-col overflow-y-auto md:flex-row">
                <div class="h-32 md:h-auto md:w-1/2">
                    <img
                            aria-hidden="true"
                            class="object-cover w-full h-full dark:hidden"
                            src="{% static 'salary/img/login-office.jpeg' %}"
                            alt="Office"
                    />
                    <img
                            aria-hidden="true"
                            class="hidden object-cover w-full h-full dark:block"
                            src="{% static 'salary/img/login-office-dark.jpeg' %}"
                            alt="Office"
                    />
                </div>
                <div class="flex items-center justify-center p-6 sm:p-12 md:w-1/2">
                    <div class="w-full">
                        <h1
                                class="mb-4 text-xl font-semibold text-gray-700 dark:text-gray-200"
                        >
                            ورود
                        </h1>
                        <form action="{% url 'accounts:login' %}" method="post">
                            {% csrf_token %}
                            {% if error %}
                                <div class="bg-red-100 rounded-lg py-5 px-6 mb-3 text-base text-red-700 inline-flex items-center w-full"
                                     role="alert">
                                    <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="times-circle"
                                         class="w-4 h-4 ml-2 fill-current" role="img" xmlns="http://www.w3.org/2000/svg"
                                         viewBox="0 0 512 512">
                                        <path fill="currentColor"
                                              d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm121.6 313.1c4.7 4.7 4.7 12.3 0 17L338 377.6c-4.7 4.7-12.3 4.7-17 0L256 312l-65.1 65.6c-4.7 4.7-12.3 4.7-17 0L134.4 338c-4.7-4.7-4.7-12.3 0-17l65.6-65-65.6-65.1c-4.7-4.7-4.7-12.3 0-17l39.6-39.6c4.7-4.7 12.3-4.7 17 0l65 65.7 65.1-65.6c4.7-4.7 12.3-4.7 17 0l39.6 39.6c4.7 4.7 4.7 12.3 0 17L312 256l65.6 65.1z"></path>
                                    </svg>
                                    {{ error }}
                                </div>
                            {% endif %}
                            <label class="block text-sm">
                                <span class="text-gray-700 dark:text-gray-400">ایمیل</span>
                                <input
                                        class="block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out mt-1 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input"
                                        placeholder="ایمیل"
                                        name="email"
                                />
                            </label>
                            <label class="block mt-4 text-sm">
                                <span class="text-gray-700 dark:text-gray-400">گذرواژه</span>
                                <input
                                        class="block w-full px-3 py-1.5 font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input"
                                        placeholder="گذرواژه"
                                        type="password"
                                        name="password"
                                />
                            </label>

                            <!-- You should use a button here, as the anchor is only used for the example  -->
                            <button type="submit"
                                    class="block w-full px-4 py-2 mt-4 text-sm font-medium leading-5 text-center text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">
                                ورود
                            </button>
                        </form>

                        <hr class="my-8"/>

                        <button
                                class="flex items-center justify-center w-full px-4 py-2 text-sm font-medium leading-5 text-white text-gray-700 transition-colors duration-150 border border-gray-300 rounded-lg dark:text-gray-400 active:bg-transparent hover:border-gray-500 focus:border-gray-500 active:text-gray-500 focus:outline-none focus:shadow-outline-gray"
                        >
                            <svg
                                    class="w-4 h-4 ml-2"
                                    aria-hidden="true"
                                    viewBox="0 0 24 24"
                                    fill="currentColor"
                            >
                                <path
                                        d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"></path>
                            </svg>
                            Github
                        </button>
                        <button
                                class="flex items-center justify-center w-full px-4 py-2 mt-4 text-sm font-medium leading-5 text-white text-gray-700 transition-colors duration-150 border border-gray-300 rounded-lg dark:text-gray-400 active:bg-transparent hover:border-gray-500 focus:border-gray-500 active:text-gray-500 focus:outline-none focus:shadow-outline-gray"
                        >
                            <svg
                                    class="w-4 h-4 ml-2"
                                    aria-hidden="true"
                                    viewBox="0 0 24 24"
                                    fill="currentColor"
                            >
                                <path
                                        d="M23.954 4.569c-.885.389-1.83.654-2.825.775 1.014-.611 1.794-1.574 2.163-2.723-.951.555-2.005.959-3.127 1.184-.896-.959-2.173-1.559-3.591-1.559-2.717 0-4.92 2.203-4.92 4.917 0 .39.045.765.127 1.124C7.691 8.094 4.066 6.13 1.64 3.161c-.427.722-.666 1.561-.666 2.475 0 1.71.87 3.213 2.188 4.096-.807-.026-1.566-.248-2.228-.616v.061c0 2.385 1.693 4.374 3.946 4.827-.413.111-.849.171-1.296.171-.314 0-.615-.03-.916-.086.631 1.953 2.445 3.377 4.604 3.417-1.68 1.319-3.809 2.105-6.102 2.105-.39 0-.779-.023-1.17-.067 2.189 1.394 4.768 2.209 7.557 2.209 9.054 0 13.999-7.496 13.999-13.986 0-.209 0-.42-.015-.63.961-.689 1.8-1.56 2.46-2.548l-.047-.02z"></path>
                            </svg>
                            Twitter
                        </button>

                        <p class="mt-4">
                            <a class="text-sm font-medium text-purple-600 dark:text-purple-400 hover:underline"
                               href="{% url 'accounts:forgot_password' %}">
                                گذرواژه خود را فراموش کردید؟
                            </a>
                        </p>
                        <p class="mt-1">
                            <a
                                    class="text-sm font-medium text-purple-600 dark:text-purple-400 hover:underline"
                                    href="{% url 'accounts:register_user' %}"
                            >
                                ایجاد حساب کاربری
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </html>
{% endblock %}

templates/accounts/pages/reset_password_email.html
{% autoescape off %}

 سلام {{ user }} عزیز

لطفاً برای بازنشانی گذرواژه خود روی لینک زیر کلیک کنید .

http://{{ domain }}{% url 'accounts:reset_password_validate' uidb64=uid token=token %}

اگر این شما نیستید، این ایمیل را نادیده بگیرید.

{% endautoescape %}