core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('salary.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('person/', include('person.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

person/urls.py
from django.urls import path
from . import views

app_name = 'person'

urlpatterns = [
    path('persons/', views.persons, name='persons'),
    path('add_person/', views.add_person, name='add_person'),
    path('person_detail/<str:nation_code>/', views.person_detail, name='person_detail'),
    path('decrees/', views.decrees, name='decrees'),
    path('add_decree/', views.add_decree, name='add_decree'),
    # path('add_decree/<slug:personal_code>/', views.add_person_decree, name='add_person_decree'),
    path('wages/', views.wages, name='wages'),
    path('add_wage/', views.add_wage, name='add_wage'),
    path('wage_detail/<int:wage_id>/<str:wage_year>/', views.wage_detail, name='wage_detail'),
]

person/models.py
from PIL.ImImagePlugin import number
from django.db import models
from django.urls import reverse

from company.models import Company


class Person(models.Model):
    class Meta:
        verbose_name = "شخص"
        verbose_name_plural = "شخص"

    MARITAL_STATUS = (
        ('Single', 'مجرد'),
        ('Married', 'متأهل')
    )
    company = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name='person_company', null=True, verbose_name='شرکت')
    personnel_code = models.CharField('کد پرسنلی', max_length=10)
    first_name = models.CharField('نام', max_length=50)
    last_name = models.CharField('نام خانوادگی', max_length=50)
    nation_code = models.CharField('کد ملی', max_length=10)
    # id_code = models.CharField('کد', max_length=10)
    image = models.ImageField('عکس', upload_to='images/persons/', default='images/profile.png')
    date_of_birth = models.DateField('تاریخ تولد', null=True, blank=True)
    place_of_birth = models.CharField('محل تولد', max_length=50, null=True, blank=True)
    father_name = models.CharField('نام پدر', max_length=50, null=True, blank=True)
    education_degree = models.CharField('مدرک تحصیلی', max_length=50, null=True, blank=True)
    number_of_children = models.IntegerField('تعداد فرزندان', default=0)
    marital_status = models.CharField(
        'وضعیت تأهل', max_length=20, choices=MARITAL_STATUS)
    account_number = models.CharField('شماره حساب بانکی', max_length=20, null=True, blank=True)
    is_active = models.BooleanField('فعال', default=False)
    created = models.DateTimeField('ایجاد شده در', auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def full_name(self):
        return self.last_name + ' ' + self.first_name

    def __str__(self):
        return '{} - {} {}'.format(self.personnel_code, self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse("person:person_detail", kwargs={"nation_code": self.nation_code})

person/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404

from company.models import Company
from person.forms import PersonForm, DecreeForm, SalaryReceiptForm
from person.models import Person
from salary.models import Decree, SalaryReceipt
from salary.views import represents_int
from django.template.defaulttags import register


@login_required
def persons(request):
    all_person = Person.objects.filter(company__accountant=request.user).order_by('-created')
    context = {
        'persons': all_person,
    }

    if request.method == 'POST':
        # print('request: ', request.POST.getlist)
        try:
            company = request.POST['company']
            person = Person.objects.filter(company__accountant=request.user, company__name__exact=company)
            if 'activate' in request.POST:
                print('activate')
                personnel_code = request.POST['p_code']
                get_person = get_object_or_404(person, personnel_code=personnel_code)
                get_person.is_active = True
                get_person.save()
            if 'deactivate' in request.POST:
                print('deactivate')
                personnel_code = request.POST['p_code']
                get_person = get_object_or_404(person, personnel_code=personnel_code)
                get_person.is_active = False
                get_person.save()
            if 'delete' in request.POST:
                print('delete')
                personnel_code = request.POST['p_code']
                # nation_code = request.POST['nation_code']
                get_person = get_object_or_404(person, personnel_code=personnel_code)
                get_person.delete()

            return redirect('person:persons')
        except Exception as e:
            context['error'] = str(e)
            return render(request, 'person/persons.html', context)
    return render(request, 'person/persons.html', context)


@login_required
def add_person(request):
    persons = Person.objects.filter(company__accountant=request.user)
    print('persons: ', persons)
    if request.method == 'POST':
        details = PersonForm(request.POST, request.FILES, request=request)
        person_n_code = persons.filter(nation_code=request.POST['nation_code'], company=request.POST['company'])
        person_p_code = persons.filter(personnel_code=request.POST['personnel_code'], company=request.POST['company'])
        print('person: ', person_p_code)

        if details.is_valid():
            try:
                if person_n_code.exists():
                    raise Exception('کد ملی تکراری است!')

                if person_p_code.exists():
                    raise Exception('کد پرسنلی تکراری است!')

                print('form is valid')
                new_person = details.save(commit=False)
                company_id = request.POST['company']
                print('company name get by form: ', company_id)
                company = Company.objects.get(id=company_id, accountant=request.user)
                print('company: ', company)
                assert company.is_active == True, 'وضعیت شرکت مورد نظر تایید نشده است. برای تایید به صفحه شرکت ها ' \
                                                  'رفته و گزینه تایید شرکت مورد نظر را بزنید.'
                new_person.date_of_birth = request.POST.get('date_of_birth')
                new_person.accountant = request.user
                new_person.save()
                return redirect('person:persons')
            except Exception as e:
                return render(request, 'person/add_person.html', {'form': details, 'error': str(e)})
        else:
            print('form is not valid')
            return render(request, 'person/add_person.html', {'form': details, 'error': 'در ثبت فرم خطایی رخ داد!'})
    else:
        form = PersonForm(request=request)
        return render(request, 'person/add_person.html', {'form': form})


@login_required
def decrees(request):
    all_decrees = Decree.objects.filter(created_by=request.user)
    context = {
        'decrees': all_decrees,
    }
    if request.method == 'POST':
        if 'delete' in request.POST:
            print('delete')
            decree_id = request.POST['delete']
            get_decree = get_object_or_404(Decree, id=decree_id)
            get_decree.delete()
            return redirect('person:decrees')
    return render(request, 'person/decrees.html', context)


@login_required
def add_decree(request):
    if request.method == 'POST':
        details = DecreeForm(request.POST, request=request)
        person = request.POST['person']
        year = request.POST['year']
        job_title = request.POST['job_title']
        base_salary = request.POST['base_salary']
        right_of_children = request.POST['right_of_children']
        right_to_housing = request.POST['right_to_housing']
        right_to_grocery = request.POST['right_to_grocery']

        is_decree = Decree.objects.filter(person=person, year__exact=year)
        print('decree: ', is_decree)
        try:
            get_person = Person.objects.get(id=person)
            print('person: ', person)
            assert get_person.is_active == True, 'برای صدور حکم، باید وضعیت کاربر تایید شده باشد!'
            assert not is_decree.exists(), 'برای این کاربر در سال مورد نظر قبلاً حکم صادر شده است!'
            assert len(year) > 0, 'سال را وارد کنید'
            assert represents_int(year), 'فرمت سال باید یک عدد صحیح 4 رقمی باشد'
            assert len(job_title) > 0, 'عنوان شغلی را وارد کنید'
            assert len(job_title) > 3, 'تعدا کاراکترهای عنوان شغلی باید از 3 بیشتر باشد'
            assert len(base_salary) > 0, 'حقوق پایه را وارد کنید'
            assert represents_int(base_salary), 'فرمت حقوق پایه باید یک عدد صحیح باشد!'
            assert not int(base_salary) == 0, 'حقوق پایه باید از 0 بزرگتر باشد!'
            assert len(right_of_children) > 0, 'حق اولاد را وارد کنید'
            assert represents_int(right_of_children), 'فرمت حقوق اولاد باید یک عدد صحیح باشد!'
            assert not int(right_of_children) == 0, 'حق اولاد باید از 0 بزرگتر باشد!'
            print('base_salary: ', int(base_salary) * 3)
            print('right_of_children: ', int(right_of_children))
            assert int(right_of_children) == int(base_salary) * 3, 'حق اولاد(ماهانه) باید معادل 3 برابر حقوق روزانه ' \
                                                                   'باشد ! '
            assert represents_int(right_of_children), 'فرمت حق اولاد باید یک عدد صحیح باشد!'
            assert len(right_to_housing) > 0, 'حق مسکن را وارد کنید'
            assert represents_int(right_to_housing), 'فرمت حق مسکن باید یک عدد صحیح باشد!'
            assert not int(right_to_housing) == 0, 'حق مسکن باید از 0 بزرگتر باشد!'
            assert len(right_to_grocery) > 0, 'حق خوار و بار را وارد کنید'
            assert represents_int(right_to_grocery), 'فرمت حق خوار و بار باید یک عدد صحیح باشد!'
            assert not int(right_to_grocery) == 0, 'حق خوار و بار باید از 0 بزرگتر باشد!'

            if details.is_valid():
                print('form is valid')
                new_decree = details.save(commit=False)
                new_decree.created_by = request.user
                new_decree.save()
                return redirect('person:decrees')
        except Exception as e:
            print('form is not valid')
            return render(request, 'person/add_decree.html', {'form': details, 'error': str(e)})
    else:
        form = DecreeForm(request=request)
        return render(request, 'person/add_decree.html', {'form': form})


@login_required
def wages(request):
    all_wage = SalaryReceipt.objects.filter(created_by=request.user)

    context = {
        'wages': all_wage,
    }
    if request.method == 'POST':
        if 'delete' in request.POST:
            print('delete')
            wage_id = request.POST['delete']
            get_wage = get_object_or_404(SalaryReceipt, id=wage_id)
            get_wage.delete()
            return redirect('person:wages')
    return render(request, 'person/wages.html', context)


@login_required
def add_wage(request):
    if request.method == 'POST':
        details = SalaryReceiptForm(request.POST, request=request)
        person = request.POST['person']
        month_name = request.POST['month_name']
        year = request.POST['year']
        working_days = request.POST['working_days']
        overtime = request.POST['overtime']
        closed_work = request.POST['closed_work']
        mission = request.POST['mission']

        weekly_days = {
            'Farvardin': '31',
            'Ordibehesht': '31',
            'Khordad': '31',
            'Tir': '31',
            'Mordad': '31',
            'Shahrivar': '31',
            'Mehr': '30',
            'Aban': '30',
            'Azar': '30',
            'Dey': '30',
            'Bahman': '30',
            'Esfand': '29',
        }

        try:
            assert len(year) > 0, 'سال را وارد کنید'
            assert represents_int(year), 'فرمت سال باید یک عدد صحیح 4 رقمی باشد'
            is_decree = Decree.objects.filter(person=person, year__exact=year)
            assert is_decree.exists(), 'برای این کاربر در سال مورد نظر هیچ حکمی صادر نشده است!'
            is_wage = SalaryReceipt.objects.filter(person=person, month_name__exact=month_name, year__exact=year)
            # assert len(is_wage) == 0, 'برای این کاربر در ماه مورد نظر فیش صادر شده است!'
            print('wage: ', is_wage)
            assert represents_int(working_days), 'فرمت روزهای کارکرد باید یک عدد صحیح باشد!'
            # number_of_days = 0
            for key, value in weekly_days.items():
                if month_name == key:
                    number_of_days = int(weekly_days[key])
                    assert int(working_days) <= number_of_days, \
                        f'تعداد روزهای ماه انتخاب شده نمی تواند از {number_of_days} بیشتر باشد!'

templates/person/wages.html
{% extends 'accounts/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block head %}
    {% block extra_headers %}
        <head>
            <meta charset="UTF-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            <link rel="stylesheet" href="{% static 'salary/css/output.css' %}">
            <title>حقوق و دستمزد - فیش حقوقی</title>
            <link
                    href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
                    rel="stylesheet"
            />
            <script
                    src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"
                    defer
            ></script>
            <script src="{% static 'salary/js/init-alpine.js' %}"></script>
            <link
                    rel="stylesheet"
                    href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css"
            />
            <script
                    src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"
                    defer
            ></script>
            <script src=".{% static 'salary/js/charts-lines.js' %}" defer></script>
            <script src="{% static 'salary/js/charts-pie.js' %}" defer></script>
        </head>
    {% endblock %}
{% endblock %}
{% block title %}{{ super }} داشبورد {% endblock %}
{% block body %}
    <div class="flex flex-col flex-1 w-full">
        <h2
                class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200"
        >
            فیش حقوقی
        </h2>
        <div class="w-40 my-8">
            <a href="{% url 'person:add_wage' %}"
               class="flex items-center justify-between w-full px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
            >
                صدور فیش حقوقی جدید
                <span class="mr-2" aria-hidden="true">+</span>
            </a>
        </div>

        <!-- Cards -->
        <div class="grid gap-6 mb-8 md:grid-cols-2 xl:grid-cols-4">
            <!-- Card -->
            <div
                    class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
            >
                <div
                        class="p-3 ml-4 text-orange-500 bg-orange-100 rounded-full dark:text-orange-100 dark:bg-orange-500"
                >
                    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                        <path
                                d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z"
                        ></path>
                    </svg>
                </div>
                <div>
                    <p
                            class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400"
                    >
                        کل شرکت ها
                    </p>
                    <p
                            class="text-lg font-semibold text-gray-700 dark:text-gray-200"
                    >
                        {#                                                {{ company.count }}#}
                    </p>
                </div>
            </div>
            <!-- Card -->
            <div
                    class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
            >
                <div
                        class="p-3 ml-4 text-green-500 bg-green-100 rounded-full dark:text-green-100 dark:bg-green-500"
                >
                    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                        <path
                                fill-rule="evenodd"
                                d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z"
                                clip-rule="evenodd"
                        ></path>
                    </svg>
                </div>
                <div>
                    <p
                            class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400"
                    >
                        تعداد کل پرسنل
                    </p>
                    <p
                            class="text-lg font-semibold text-gray-700 dark:text-gray-200"
                    >
                        {{ persons.count }}
                    </p>
                </div>
            </div>
            <!-- Card -->
            <div
                    class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
            >
                <div
                        class="p-3 ml-4 text-blue-500 bg-blue-100 rounded-full dark:text-blue-100 dark:bg-blue-500"
                >
                    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                        <path
                                d="M3 1a1 1 0 000 2h1.22l.305 1.222a.997.997 0 00.01.042l1.358 5.43-.893.892C3.74 11.846 4.632 14 6.414 14H15a1 1 0 000-2H6.414l1-1H14a1 1 0 00.894-.553l3-6A1 1 0 0017 3H6.28l-.31-1.243A1 1 0 005 1H3zM16 16.5a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zM6.5 18a1.5 1.5 0 100-3 1.5 1.5 0 000 3z"
                        ></path>
                    </svg>
                </div>
                <div>
                    <p
                            class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400"
                    >
                        تعداد فیش های حقوقی
                    </p>
                    <p
                            class="text-lg font-semibold text-gray-700 dark:text-gray-200"
                    >
                        {{ wages.all.count }}
                    </p>
                </div>
            </div>
            <!-- Card -->
            <div
                    class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
            >
                <div
                        class="p-3 ml-4 text-teal-500 bg-teal-100 rounded-full dark:text-teal-100 dark:bg-teal-500"
                >
                    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                        <path
                                fill-rule="evenodd"
                                d="M18 5v8a2 2 0 01-2 2h-5l-5 4v-4H4a2 2 0 01-2-2V5a2 2 0 012-2h12a2 2 0 012 2zM7 8H5v2h2V8zm2 0h2v2H9V8zm6 0h-2v2h2V8z"
                                clip-rule="evenodd"
                        ></path>
                    </svg>
                </div>
                <div>
                    <p
                            class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400"
                    >
                        مخاطبین معلق
                    </p>
                    <p
                            class="text-lg font-semibold text-gray-700 dark:text-gray-200"
                    >
                        35
                    </p>
                </div>
            </div>
        </div>

        {% if wages %}
            <!-- New Table -->
            <div class="w-full overflow-hidden rounded-lg shadow-xs">
                <div class="w-full overflow-x-auto">
                    <table class="w-full whitespace-no-wrap">
                        <thead>
                        <tr
                                class="text-xs font-semibold tracking-wide text-right text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800"
                        >
                            <th class="px-4 py-3">کد پرسنلی</th>
                            <th class="px-4 py-3">نام پرسنل</th>
                            <th class="px-4 py-3">نام شرکت</th>
                            <th class="px-4 py-3">سال و ماه فیش</th>
                            <th class="px-4 py-3">روزهای کارکرد</th>
                            <th class="px-4 py-3">تاریخ ثبت</th>
                            <th class="px-4 py-3">عملیات</th>
                        </tr>
                        </thead>
                        <tbody
                                class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800"
                        >

                        {% for wage in wages %}
                            <tr class="text-gray-700 dark:text-gray-400">
                                <td class="px-4 py-3 text-sm">
                                    {{ wage.person.personnel_code }}
                                </td>
                                <td class="px-4 py-3">
                                    <div class="flex items-center text-sm">
                                        <div>
                                            <p class="font-semibold">
                                                {{ wage.person.full_name }}
                                            </p>
                                        </div>
                                    </div>
                                </td>
                                <td class="px-4 py-3 text-sm">
                                    {{ wage.person.company.name }}
                                </td>
                                <td class="px-4 py-3 text-sm">
                                    {{ wage.month_name }}/{{ wage.year }}
                                </td>
                                <td class="px-4 py-3 text-sm">
                                    {{ wage.working_days }}
                                </td>
                                <td class="px-4 py-3 text-sm">
                                    {{ wage.created | date:"M d, Y" }}
                                </td>
                                <td class="px-4 py-3 text-xs flex justify-start">
                                    <div class="flex-model gap-2">
                                        <a href="{% url 'person:wage_detail' wage.id wage.year %}" class="hover:text-blue-700"
                                           data-bs-toggle="tooltip" data-bs-placement="top" title="مشاهده فیش حقوقی">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                 stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                                <path stroke-linecap="round" stroke-linejoin="round"
                                                      d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z"></path>
                                                <path stroke-linecap="round" stroke-linejoin="round"
                                                      d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                                            </svg>
                                        </a>
                                        <a href="#" class="hover:text-blue-700"
                                        data-bs-toggle="tooltip" data-bs-placement="top" title="ویرایش فیش حقوقی">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                 stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                                <path stroke-linecap="round" stroke-linejoin="round"
                                                      d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"></path>
                                            </svg>

                                        </a>
                                        <form action="" method="post">
                                            {% csrf_token %}
                                            <div>
                                                <button type="submit" name="delete" value="{{ wage.id }}"
                                                        class="px-2 py-1 font-bold leading-tight text-red-50 bg-red-600 rounded hover:bg-red-700 tr-model-100">
                                                    حذف
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% else %}
            <!-- Card -->
            <div class="flex items-center p-4 bg-red-100 text-red-700 rounded-lg shadow-xs dark:bg-gray-800">
                <div class="flex-model mx-auto">
                    <span class="mb-2 text-sm text-center font-medium">
                        هیچ فیش حقوقی یافت نشد !
                    </span>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}